### ISSUE TITLE
Возврат тасков из методов

### ISSUE THREAD

**Issue by mitsusi** [causer/Itasu#4]
в таких местах лучше сразу вернуть Task без await

*Itasu/src/Itasu.Core/Security/Services/RoleService.cs
 public async Task<IdentityResult> CreateAsync(SiteRole role)
+        {
+            return await _roleManager.CreateAsync(role);
+        }

**Comment by causer** [comment]
Расскажи, пожалуйста, разницу с использованием async/await и без.

**Comment by mitsusi** [comment]
Да я тут не особо-то что и расскажу, но в записи в сабже нет смысла и пользы тоже. Смысл загонять таску в пул потоков, если в вызове выше уровнем все равно будет вызов через await? Вот можно прочесть http://lambdy.ru/post/42202826803/c-async . Кстати, первый коммент к статье про транзакции в ADO.NET порадовал, надо будет в проект на работе заглянуть))

**Comment by mitsusi** [comment]
а, еще один момент про конфигурацию контекста. Лучше вызывать асинхронные методы с добавкой ConfigureAwait(false). Ну и более подробно в очень полезной статье https://msdn.microsoft.com/ru-ru/magazine/jj991977.aspx

**Comment by causer** [comment]
Да, похоже на правду. Вот тут обсуждение: http://stackoverflow.com/questions/19098143/what-is-the-purpose-of-return-await-in-c
Получается, помечая метод как async (в данном случае) мы создаем лишнюю таску, а внутри неё ждём выполнение другой таски.
